# Generated by Django 3.2.25 on 2025-01-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='confusable_plant_image',
            field=models.ImageField(blank=True, help_text='Upload an image of the confusable plant, if applicable.', null=True, upload_to='images/', verbose_name='Confusable Plant Image'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='confusable_plant_information',
            field=models.TextField(blank=True, help_text='Describe distinguishing features of the confusable plant.', null=True, verbose_name='Confusable Plant Environment'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='confusable_plant_name',
            field=models.CharField(blank=True, help_text='Common name of confuseable plant.', max_length=255, null=True, verbose_name='Confusable Plant Name'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='confusable_plant_warnings',
            field=models.TextField(blank=True, help_text='Dangers of mistaking this plant for the main plant', null=True, verbose_name='Confusable Plant Warnings'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Automatically sets date & time when the record is created.', verbose_name='Creation Date and Time'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='history_and_folklore',
            field=models.TextField(default='', help_text='Provide any historical and folklore information for plant.', verbose_name='History and Folklore'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='main_plant_environment',
            field=models.TextField(default='', help_text='Describe likely environment of plant', verbose_name='Main Plant Environment'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='main_plant_parts_used',
            field=models.TextField(default='', help_text='Specify the parts of the plant that are useful.', verbose_name='Usable Plant Parts'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='main_plant_warnings',
            field=models.TextField(blank=True, help_text='Potential warnings related to the plant', null=True, verbose_name='Plant Warnings'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='medicinal_uses',
            field=models.TextField(blank=True, default='', help_text='Describe the medicinal uses of main plant', null=True, verbose_name='Medicinal Uses'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Automatically sets the date and time of the last update.', verbose_name='Updated Date and Time'),
        ),
    ]
