# Generated by Django 3.2.4 on 2024-11-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantinfocuspost',
            name='folklore',
        ),
        migrations.AddField(
            model_name='plantinfocuspost',
            name='history_and_folklore',
            field=models.TextField(default='', help_text='Provide any historical and folklore information about themain plant.', verbose_name='History and Folklore'),
        ),
        migrations.AddField(
            model_name='plantinfocuspost',
            name='main_plant_parts_used',
            field=models.TextField(default='Unknown', help_text='Specify parts of the plant that are of use', verbose_name='Usable plant parts'),
        ),
        migrations.AddField(
            model_name='plantinfocuspost',
            name='main_plant_warnings',
            field=models.TextField(blank=True, help_text='Mention any warnings related to the plant that usersshould be aware of.', null=True, verbose_name='Plant warnings'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='confusable_plant_image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/cheymd/image/upload/v1731064102/media/images/default_plant_image_rvlqpb.jpg', help_text='Upload an image of the confusable plant, if needed', max_length=255, null=True, upload_to='images/', verbose_name='Confusable Plant Image'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='confusable_plant_warnings',
            field=models.TextField(blank=True, help_text='Describe any dangers of mistaking this plant for the main_plant of interest', null=True, verbose_name='warnings'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Automatically sets date & time when the record is created', verbose_name='Creation Date and Time'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='main_plant_image',
            field=models.ImageField(default='https://res.cloudinary.com/cheymd/image/upload/v1731064102/media/images/default_plant_image_rvlqpb.jpg', help_text='Upload an image of the main plant.', max_length=255, upload_to='images/', verbose_name='Main Plant Image'),
        ),
    ]
