# Generated by Django 3.2.25 on 2025-01-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_blog', '0002_auto_20250113_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='confusable_plant_image',
            field=models.ImageField(blank=True, help_text='Upload an image of the confusable plant, if needed', null=True, upload_to='images/', verbose_name='Confusable Plant Image'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='confusable_plant_information',
            field=models.TextField(blank=True, help_text='Describe distinguishing features', null=True, verbose_name='Confusable Plant Environment'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='confusable_plant_name',
            field=models.CharField(blank=True, help_text='Enter the common name of the plant that can be confused with the main plant.', max_length=255, null=True, verbose_name='Confusable Plant Name'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='confusable_plant_warnings',
            field=models.TextField(blank=True, help_text='Describe any dangers of mistaking this plant for the main_plant of interest', null=True, verbose_name='warnings'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Automatically sets date & time when the record is created', verbose_name='Creation Date and Time'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='history_and_folklore',
            field=models.TextField(default='', help_text='Provide any historical and folklore information about themain plant.', verbose_name='History and Folklore'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='main_plant_environment',
            field=models.TextField(default='', help_text='Describe the environment where the main plant is likely to be found.', verbose_name='Main Plant Environment'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='main_plant_parts_used',
            field=models.TextField(default='', help_text='Specify parts of the plant that are of use', verbose_name='Usable plant parts'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='main_plant_warnings',
            field=models.TextField(blank=True, help_text='Mention any warnings related to the plant that usersshould be aware of.', null=True, verbose_name='Plant warnings'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='medicinal_uses',
            field=models.TextField(blank=True, default='', help_text='Describe the medicinal uses of the main plant.', null=True, verbose_name='Medicinal Uses'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Automatically adds date  time of update.', verbose_name='Updated date & time.'),
        ),
    ]
