# Generated by Django 3.2.4 on 2024-10-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants_blog", "0002_auto_20241003_0341"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantinfocuspost",
            name="folklore",
        ),
        migrations.AddField(
            model_name="plantinfocuspost",
            name="history_and_folklore",
            field=models.TextField(
                default="",
                help_text="Provide any historical and folklore information about themain plant.",
                verbose_name="History and Folklore",
            ),
        ),
        migrations.AlterField(
            model_name="plantinfocuspost",
            name="main_plant_warnings",
            field=models.TextField(
                blank=True,
                help_text="Mention any warnings related to the plant that usersshould be aware of.",
                null=True,
                verbose_name="Plant warnings",
            ),
        ),
    ]
