# Generated by Django 3.2.4 on 2024-11-11 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants_blog', '0003_auto_20241111_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantinfocuspost',
            name='main_plant_image',
        ),
    ]
