# Generated by Django 3.2.4 on 2024-10-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_blog', '0003_auto_20241016_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='confusable_plant_image',
            field=models.ImageField(blank=True, default='v1706847130/foraging_link/plant_images/default_foraged_image_vev3ib.jpg', help_text='Upload an image of the confusable plant, if needed', null=True, upload_to='foraging_link/plant_images', verbose_name='Confusable Plant Image'),
        ),
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='main_plant_image',
            field=models.ImageField(default='v1706847130/foraging_link/plant_images/default_foraged_image_vev3ib.jpg', help_text='Upload an image of the main plant.', upload_to='foraging_link/plant_images', verbose_name='Main Plant Image'),
        ),
    ]
