# Generated by Django 3.2.4 on 2024-11-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_blog', '0004_remove_plantinfocuspost_main_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantinfocuspost',
            name='main_plant_image',
            field=models.ImageField(default='images/default_plant_image_rvlqpb', help_text='Upload an image of the main plant.', upload_to='images/', verbose_name='Main Plant Image'),
        ),
    ]
