# Generated by Django 3.2.25 on 2024-11-28 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants_blog', '0006_auto_20241127_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantinfocuspost',
            name='confusable_plant_image',
        ),
    ]
