# Generated by Django 3.2.25 on 2024-11-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_blog', '0008_plantinfocuspost_confusable_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinfocuspost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Automatically adds date  time of update.', verbose_name='Updated date & time.'),
        ),
    ]
