# Generated by Django 3.2.4 on 2024-11-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants_blog', '0008_auto_20241109_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantinfocuspost',
            name='confusable_plant_image',
        ),
        migrations.RemoveField(
            model_name='plantinfocuspost',
            name='main_plant_image',
        ),
    ]
