# Generated by Django 3.2.25 on 2024-11-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants_blog', '0009_alter_plantinfocuspost_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantinfocuspost',
            name='confusable_plant_image',
        ),
        migrations.RemoveField(
            model_name='plantinfocuspost',
            name='confusable_plant_information',
        ),
        migrations.RemoveField(
            model_name='plantinfocuspost',
            name='confusable_plant_name',
        ),
        migrations.RemoveField(
            model_name='plantinfocuspost',
            name='confusable_plant_warnings',
        ),
    ]
