# Generated by Django 3.2.4 on 2024-11-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_blog', '0016_auto_20241109_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantinfocuspost',
            name='confusable_plant_image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/cheymd/image/upload/v1731064102/media/images/default_plant_image_rvlqpb.jpg', help_text='Upload an image of the confusable plant, if needed', max_length=500, null=True, upload_to='images/', verbose_name='Confusable Plant Image'),
        ),
        migrations.AddField(
            model_name='plantinfocuspost',
            name='main_plant_image',
            field=models.ImageField(default='https://res.cloudinary.com/cheymd/image/upload/v1731064102/media/images/default_plant_image_rvlqpb.jpg', help_text='Upload an image of the main plant.', max_length=500, upload_to='images/', verbose_name='Main Plant Image'),
        ),
    ]
