# Generated by Django 3.2.4 on 2024-10-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='v1730006283/foraging_link/user_avatars/default_avatar_fqwsjf.jpg', help_text='Profile image of the user. Defaults to generic image if one is not provided', upload_to='foraging_link/user_avatars', verbose_name='Profile Image'),
        ),
    ]
