# Generated by Django 3.2.4 on 2024-10-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='v1730006283/foraging_link/user_avatars/default_avatar_fqwsjf.jpg', help_text='Profile avatar of the user. Defaults to generic avatar if one is not provided', upload_to='foraging_link/user_avatars', verbose_name='Profile avatar'),
        ),
    ]
