# Generated by Django 3.2.4 on 2024-10-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20241028_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='v1730152602/foraging_link/user_avatars/default_avatar_pqilab.jpg', help_text='Profile image of the user. Defaults to generic image if one is not provided', upload_to='foraging_link/user_avatars', verbose_name='Profile Image'),
        ),
    ]
