# Generated by Django 3.2.4 on 2024-11-10 16:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='The email address of the user.', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='The phone number of the user.', max_length=128, region='GB', verbose_name='Phone')),
                ('registration_date', models.DateTimeField(auto_now=True, help_text='The date and time of registration.', verbose_name='Registration Date')),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Confirmed', help_text='The current status of the registration.', max_length=50, verbose_name='Status')),
                ('has_dietary_restrictions', models.BooleanField(default=False, help_text='Indicates if the user has any dietary restrictions.', verbose_name='Has Dietary Restrictions')),
                ('dietary_restrictions', models.TextField(blank=True, help_text="Details of the user's dietary restrictions, if any.", null=True, verbose_name='Dietary Restrictions')),
                ('is_driver', models.BooleanField(default=False, help_text='Indicates if the user is a driver.', verbose_name='Is Driver')),
                ('has_emergency_contact', models.BooleanField(default=False, help_text='Tick if the user has an emergency contact.', verbose_name='Has Emergency Contact')),
                ('ice_name', models.CharField(help_text='Name of the emergency contact person.', max_length=255, verbose_name='Emergency Contact Name')),
                ('ice_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number for the emergency contact person.', max_length=128, region='GB', verbose_name='Emergency Contact Number')),
                ('course_title', models.ForeignKey(default=3, help_text='Enter the title of the course for this registration.', on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Course Title')),
                ('owner', models.ForeignKey(help_text='Select the user this registration belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
