# Generated by Django 3.2.4 on 2024-10-24 16:59

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('course_registrations', '0003_auto_20240927_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='has_dietary_restrictions',
            field=models.BooleanField(default=False, help_text='Indicates if the user has any dietary restrictions.', verbose_name='Has Dietary Restrictions'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='dietary_restrictions',
            field=models.TextField(blank=True, help_text="Details of the user's dietary restrictions, if any.", null=True, verbose_name='Dietary Restrictions'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='email',
            field=models.CharField(help_text='The email address of the user.', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='ice_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number for the emergency contact person.', max_length=128, region=None, verbose_name='Emergency Contact Number'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='The phone number of the user.', max_length=128, region='GB', verbose_name='Phone'),
        ),
    ]
