# Generated by Django 3.2.4 on 2024-10-27 08:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('course_registrations', '0004_auto_20241024_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='ice_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number for the emergency contact person.', max_length=128, region='GB', verbose_name='Emergency Contact Number'),
        ),
    ]
