# Generated by Django 3.2.4 on 2024-10-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registrations', '0005_alter_courseregistration_ice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='has_emergency_contact',
            field=models.BooleanField(default=False, help_text='Tick if the user has an emergency contact.', verbose_name='Has Emergency Contact'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Confirmed', help_text='The current status of the registration.', max_length=50, verbose_name='Status'),
        ),
    ]
