# Generated by Django 3.2.25 on 2025-02-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants_blog', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='plant_in_focus_post',
            field=models.ForeignKey(default=None, help_text='The post about the plant that this comment is related to.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plants_blog.plantinfocuspost', verbose_name='Plant in Focus Posts'),
        ),
    ]
