# Generated by Django 3.2.25 on 2025-01-16 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants_blog', '0003_auto_20250116_0631'),
        ('comments', '0002_alter_comment_plant_in_focus_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='plant_in_focus_post',
            field=models.ForeignKey(default=None, help_text='The post about the plant that this comment is related to.', on_delete=django.db.models.deletion.CASCADE, to='plants_blog.plantinfocuspost', verbose_name='Plant in Focus Posts'),
        ),
    ]
