# Generated by Django 3.2.25 on 2024-12-12 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('plants_blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the like was created.', verbose_name='Created At')),
                ('comment', models.ForeignKey(blank=True, help_text="The comment that's liked.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comments.comment', verbose_name='Comment')),
                ('owner', models.ForeignKey(help_text='The User who likes the post or comment.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('plant_in_focus_post', models.ForeignKey(blank=True, help_text="The plant in focus post that's liked.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='plants_blog.plantinfocuspost', verbose_name='Plant in Focus Post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('owner', 'plant_in_focus_post'), name='unique_like_per_post'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('owner', 'comment'), name='unique_like_per_comment'),
        ),
    ]
