# Generated by Django 3.2.25 on 2025-01-16 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_plant_in_focus_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants_blog', '0003_auto_20250116_0631'),
        ('likes', '0002_auto_20250113_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, help_text="The comment that's liked.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comments.comment', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the like was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='like',
            name='owner',
            field=models.ForeignKey(help_text='The User who likes the post or comment.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='like',
            name='plant_in_focus_post',
            field=models.ForeignKey(blank=True, help_text="The plant in focus post that's liked.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='plants_blog.plantinfocuspost', verbose_name='Plant in Focus Post'),
        ),
    ]
