# Generated by Django 3.2.25 on 2025-01-14 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("followers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follower",
            name="owner",
            field=models.ForeignKey(
                help_text="The user following another user.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="follower",
            constraint=models.UniqueConstraint(
                fields=["owner", "followed"], name="unique_following"
            ),
        ),
    ]
