# Generated by Django 3.2.25 on 2025-01-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_alter_follower_owner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follower',
            name='unique_following',
        ),
    ]
